### ISSUE TITLE
results on newstest2014

### ISSUE THREAD

**Issue by apeterswu** [rsennrich/subword-nmt#25]
Hi,

I read your paper of BPE, that's a great work. I just wondering where is the result of newstest2014, seems I couldn't find the reported BLEU score. Am I missing anything?

Thanks.

**Comment by rsennrich** [comment]
Hi,

there is a recent trend to report tokenized BLEU (with multi-bleu.perl) 
on newstest2014. For the sake of comparison, I report such numbers in 
this paper: https://arxiv.org/abs/1612.04629

It's a small pet-peeve of mine that reporting tokenized BLEU scores is a 
bad practice in the field, because scores will be affected by your 
choice of tokenization scripts and settings. I typically report BLEU 
with the NIST BLEU script (mteval-v13a.perl), which takes untokenized 
text and performs its own internal tokenization, which guarantees 
consistency across systems. I've also created a variant of 
multi-bleu.perl that performs the same internal tokenization (expecting 
untokenized references and hypotheses), and produces the same scores, as 
mteval-v13a.perl: 
https://github.com/rsennrich/nematus/blob/master/data/multi-bleu-detok.perl

best wishes,
Rico

**Comment by apeterswu** [comment]
so according to Moses multi-bleu.perl, the result should be 21. It's a relative high performance. 
And thanks for your providing of other scripts.

**Comment by rsennrich** [comment]
We used a maximum length of 50 (sub)words in our experiments.
