### ISSUE TITLE
BPE and FST

### ISSUE THREAD

**Issue by loretoparisi** [rsennrich/subword-nmt#26]
I have recently found out [this](https://research.googleblog.com/2017/05/the-machine-intelligence-behind-gboard.html) post by google about the transliteration models implemented with `FST` encoder/decoder used on the Gboard keyboard. I'm not sure which is the difference between `BPE` presented [here](https://arxiv.org/pdf/1508.07909.pdf) and the FST used by Google. Any hint, thank you?

**Comment by rsennrich** [comment]
Hello Loreto,

to be honest, I don't see much similarity between the two, except that 
they both use the term "encoder".

- Our BPE implementatoin performs word segmentation into subword units. 
It does not perform translation or transliteration, but it can be 
helpful to improve the performance of a translation system because some 
translations/transliterations are easier on the subword level.

- The Google FST you refer to is a full "translation" system (consisting 
of a translation model and an n-gram language model) with no reordering 
component. See here for some more work on using FSTs for MT: 
http://www.statmt.org/survey/Topic/FiniteStateMachines

best wishes,
Rico

**Comment by loretoparisi** [comment]
@rsennrich Thank you Rico for your clarification about those two approach. In my case the closest is BPE, but I'm not sure how to *pipe* it in the whole process, so the question.
I'm using multi-language models with Facebook FastText and other char-level CNN classifiers, FairSeq for NMT, and so the first problem was with the transliteration (in the unicode charset domain) of the source text (like Chinese, arabic, etc.). 

In this context, the `BPE` should be applied before the transliteration/uni-decode in order to work on the subword, and before any kind of normalization (newline, escaping, double quotes, quotes, etc.) so using this approach:

```
source text --- (BPE) ---> subwords ---> (UniDecode/Transliterate) ---> decoded text ---> (normalization) ---> output text
```

where the latter will populate the training set as well it will be used in the same process when doing inference.

Thank you very much.
