### ISSUE TITLE
apply_bpe.py produces extra lines on specific file / codecs module

### ISSUE THREAD

**Issue by gugray** [rsennrich/subword-nmt#29]
not sure it's highly relevant, but it may be of help if someone runs into this again. when running `apply_bpe.py` on a specific file with 1.9 million lines, the script outputs 4 extra lines. after a few hours of investigation it boils down to the `codecs` module: `for line in args.input:` produces the extra 4 lines. replacing `codecs` with `io` solves the issue.

unfortunately the extra lines are at random positions in the middle and once i worked around this i didn't spend extra time on finding where they come from and what may be anomalous in the data to trigger this.

i'm happy provide the offending file on request.

**Comment by rsennrich** [comment]
Hello gugray,

I've now replaced codecs with io for python 3 - I didn't find a nice solution for python 2.7. Do you have one?

**Comment by gugray** [comment]
io worked for me when the input comes from a file. For stdin/stdout I stayed with codecs: it generally works, and I proess only the large training corpus with the file arguments. Code is less elegant that way, but it works.

**Comment by ozancaglayan** [comment]
why not dropping 2.x support @rsennrich ? :)

**Comment by yapingzhao** [comment]
Hi,all.I have a problem.
python -m learn_joint_bpe_and_vocab --input corpus.en corpus.ch -s 30000 -o bpe.codes --write-vocabulary bpe.vocab.en bpe.vocab.ch
 After running the above command, the following hints appear：no pair has frequency >= 2. Stopping。
I don't understand what this message means. I hope to give it a answer, thank you.

**Comment by rsennrich** [comment]
@gugray: I suspect this is an issue with unicode line breaks: https://stackoverflow.com/questions/17273598/python-codecs-line-ending
can you maybe check this in your files?

@yapingzhao: Please open a new issue if your problem is clearly unrelated. learn_bpe terminates under two conditions:
 - you have reached the defined number of merge operations.
 - there is no pair of subword units that occurs more than once.
if you try to learn BPE operations on a small corpus, you might encounter the second condition. Depending on your use case, this might be fine, but I would usually recommend to use a large corpus to learn BPE operations.

**Comment by gugray** [comment]
@rsennrich I am unable to verify unfortunately. I no longer have every dataset that I was working with back in August. I checked the ones that are still there for 0x1c-0x1f, but didn't find these bytes in them.

Nonetheless, the issue you're linking to does indeed seem exactly like the kind of thing that could have this outcome.

Thank you for checking!

**Comment by rsennrich** [comment]
I made two changes to apply_bpe.py that should fix this. I still recommend doing normalization of UTF-8 whitespace characters in preprocessing, since the current change means that apply_bpe.py will treat words separated by special UTF-8 whitespace characters as single words.
