### ISSUE TITLE
Apply.bpe is giving duplicates in Vocabulary result file (German-English)

### ISSUE THREAD

**Issue by mohammedayub44** [rsennrich/subword-nmt#42]
I'm trying to replicate English-German benchmarking using this link: [Tensorflow Seq-to-seq](https://www.tensorflow.org/tutorials/seq2seq ). When I closely look at result file it has duplicates like 'Flank@@' 'flank@@', 'Check-In' 'check-in'. I removed these duplicates by sorting and filtering but somehow my bleu scores get messed up (test and dev bleu scores show 0.0). I'm thinking it because I modified my vocabulary file it's reading it incorrectly. Attached is the vocab file. 
[vocab.bpe.32000.de.txt](https://github.com/rsennrich/subword-nmt/files/1876006/vocab.bpe.32000.de.txt)

**Comment by rsennrich** [comment]
those don't look like duplicates to me - the first character is uppercased in one, but not in the other.

Also, you should not touch a vocabulary file that is used by your neural toolkit to map between words and integers.

**Comment by mohammedayub44** [comment]
Sorry, I think the above case is fine, there seem to be some duplicates with Unicode characters like "��xx" etc.
Not sure if I'm doing this correctly.

Attached is the vocab file for reference. 
[vocab.bpe.32000.de.txt](https://github.com/rsennrich/subword-nmt/files/1876871/vocab.bpe.32000.de.txt)


![sub_nmt_ascii_dups02](https://user-images.githubusercontent.com/7122670/38323691-0a138f2a-380c-11e8-99fa-0cf7b269a473.png)
![sub_nmt_ascii_dups01](https://user-images.githubusercontent.com/7122670/38323692-0a2d232c-380c-11e8-98ba-ef0fe55eeebb.png)

**Comment by rsennrich** [comment]
� is a replacement character for illegal unicode strings. Which data did you use, and is it possible that it has non-UTF-8 text? I don't know the scripts behind the seq2seq tutorial too well, but it's possible that two different, invalid UTF-8 sequences are mapped to the same replacement character at some point, which causes your lookup problem.

I would be surprised if this mapping happened in learn_bpe.py or apply_bpe.py, however, since the current default behaviour is to raise an exception if the input isn't valid UTF-8. That is, unless you modified the scripts to replace invalid character rather than raise an exception.
