### ISSUE TITLE
How to use 'glossaries' field?

### ISSUE THREAD

**Issue by mzeidhassan** [rsennrich/subword-nmt#49]
Hi @rsennrich ,

Can you please shed some light on how to use the glossaries field? 
What file format? How should it be structured, etc?

Thanks,
mzeid

**Comment by rsennrich** [comment]
@DiMesq : can you improve the documentation in apply_bpe.py a bit, and answer the question here?

**Comment by mzeidhassan** [comment]
Hi @DiMesq,

Any update on this? A quick example on how to use this feature would be great. Thanks!

**Comment by mzeidhassan** [comment]
@rsennrich @DiMesq 

Can we use Regex in the glossaries file to prevent BPE tokenization on regex patterns? 

Can someone give me the command on how to pass the glossaries file please?

Thanks in advance!

**Comment by Proyag** [comment]
@mzeidhassan It doesn't accept a file for the glossaries, merely a space-separated list of words following `--glossaries` in the `apply-bpe` command. #56 enables using regex in the glossaries.

**Comment by mzeidhassan** [comment]
Thanks @Proyag for your reply. I appreciate it.

If it doesn't accept a file as an input, how would you pass a long list? Is there an efficient way to do this? 

The regex addition would be great. Thanks for this.

**Comment by Proyag** [comment]
I agree it's better to pass a file as the argument rather than a list if you have anything but a very short set of glossaries. I don't need that at the moment, so I didn't change that.
As a quick hack, I guess you could put the space-separated list into a file (say glossaries.txt), and use
`--glossaries $(cat glossaries.txt)`
