### ISSUE TITLE
Chinese word segmentation

### ISSUE THREAD

**Issue by parahaoer** [rsennrich/subword-nmt#53]
Can this tool  be used to do Chinese word segmentation?
Thank you very much!

**Comment by liesun1994** [comment]
it works.

**Comment by parahaoer** [comment]
@liesun1994 Could you please tell me how you do it?

**Comment by rsennrich** [comment]
we have previously used jieba for word segmentation, then used BPE to learn a subword segmentation: http://www.statmt.org/wmt17/pdf/WMT39.pdf

if you want to try word segmentation with BPE, you can run learn_bpe.py on unsegmented text, but note that the code was not optimized for this use case, and will likely be slower and consume more memory.

**Comment by liesun1994** [comment]
@parahaoer  for Chinese word segmentation, you can use this tool [jieba](https://github.com/fxsjy/jieba) or [stanford parser](https://nlp.stanford.edu/software/segmenter.html)

**Comment by guotong1988** [comment]
THX

**Comment by gvskalyan** [comment]
@rsennrich I used a transformer base model in fairseq as specified in [paper](http://www.statmt.org/wmt17/pdf/WMT39.pdf]) with same no of merge (59500 - separate BPE models) operations that gave around 24 M sentences except back translated data . 
But I am getting low BLEU score of 17.69 as compared to what your paper claims I use sacre BLEU to compute BLEU score which gives same BLEU as official MT eval script 
I could not find out the reason to atleast achieve the baseline

**Comment by rsennrich** [comment]
this question/complaint is very underspecified (you don't even mention the translation direction), but I don't expect your problem to be the BPE segmentation.

You can actually find most of our WMT17 submissions here: http://data.statmt.org/wmt17_systems/
Maybe this will help you find the difference to your training setup, for example in preprocessing.

**Comment by gvskalyan** [comment]
The translation direction is en -> zh i used the same [script](http://data.statmt.org/wmt17_systems/en-zh/preprocess.sh) to preprocess the data
model : transformer base with the settings and hyperparameters of vaswani et al., Please help to replicate the results. Thank you
 
Since the doubt pertains to chinese data I have posted in the same issue rather than creating a new one. Apologies

**Comment by gvskalyan** [comment]
The translation direction is en -> zh i used the same [script](http://data.statmt.org/wmt17_systems/en-zh/preprocess.sh) to preprocess the data
model : transformer base with the settings and hyperparameters of vaswani et al., Please help to replicate the results. Thank you
 
Since the doubt pertains to chinese data I have posted in the same issue rather than creating a new one. Apologies
