### ISSUE TITLE
Vocabulary size

### ISSUE THREAD

**Issue by casperkaae** [rsennrich/subword-nmt#6]
Hi Rico

First, thanks a lot for releasing your code!

I have a few questions w.r.t. to the implementation/usage

1. I tried to learn a model/codes  on the french europarl corpus and encode the same text using the learned model. When I use  5000 or 10000 symbols i get a vocabulary size of 5464 and 10435 respectively on the encoded text. (checked using the script `get_vocab` on the encoded text. The trained models/code files do contain 5000 or 10000 lines as expected). I this intended behaviour or am I doing something wrong?

3. Whats the best way to process the encoded text downstream of `apply_bpe.py`. Should i just encoded as i would normally with a space separated tokenized text - Specifically I'm thinking how you go about extracting the vocabulary, do you get that from the model/codes file or extract that from the encoded text? 

BR 
Casper Sønderby

**Comment by rsennrich** [comment]
Hello Casper,

1. the vocabulary in the corpus is typically the number of characters plus the number of BPE merge operations (with a few exceptions, especially if you learn BPE on the joint vocabulary). So yes, it is normal that the vocabulary size exceeds the number of BPE symbols. In our experiments, we set the network vocabulary to be slightly larger than the number of BPE operations (60000 and 59500, respectively).

2. we extract the vocabulary from the encoded text, like we do for the unsegmented text. Again, this is because the BPE model does not contain entries for characters, which should also be part of the network vocabulary.

best wishes,
Rico

**Comment by casperkaae** [comment]
Hi

Ah yes, it makes that number of unique tokens is merge-operations+characters - thanks for clarifying that!

Thanks 
Casper
