### ISSUE TITLE
encoding issue?

### ISSUE THREAD

**Issue by kmario23** [rsennrich/subword-nmt#63]
Hi,
  I have been using this code for sometime but lately I've been getting this issue. 

`no pair has frequency >= 2. Stopping`

What's strange about this is that it works with some input files whereas it fails with the above message for some files (although these are exactly in the same format as required)

What exactly is the problem? Also, any ideas about how to fix this? I have already tried the solution suggested in #29 but that didn't help much.

thanks!

**Comment by rsennrich** [comment]
that isn't necessarily an error. It can happen if your input file is relatively small, and/or your set number of merge operations relatively large. If there is no pair of subword units occurring multiple times, the learn_bpe script will not produce any more merge operations, but you can continue to apply the BPE file as usual (although I would recommend reducing the number of merge operations, because you're unlikely to learn a good representation for subword units that occur only twice in your corpus).

**Comment by kmario23** [comment]
@rsennrich Thanks a lot for the nice explanation :+1: I was indeed using a relatively small number of sentences in the file (~200) but with `--symbols 32K`. This clarifies the issue!
