### ISSUE TITLE
Vocabulary size / convention

### ISSUE THREAD

**Issue by Kyubyong** [rsennrich/subword-nmt#67]
Hi Reco,

You mentioned the vocabulary size is the number of characters + # bpe_operations. Does that mean the network is based on characters and bpes, not (words and bpes)? For example, for the following text which is segmented using bpes, what's the vocabulary size?

e.g.,
low lo@@ w@@ e@@ r

If we count characters and bpes: 7
Or if we count words and bpes: 5

**Comment by rsennrich** [comment]
If a word is represented as a single symbol, then this is a result of BPE merge operations. So if you want to determine the subword vocabulary size after applying BPE, the upper bound is 2x (character vocabulary size) + the number of merge operations. (The factor of 2 comes in because each character can be word-final or not).

In practice, your training set vocabulary can be smaller because not all character or subword units appear in isolation (without being merged into larger subword units). In the example above, you have 5 characters (l, o, w, e, r) and 2 BPE merge operations (l+o@@->lo@@ ; lo@@+w->low), which gives you a theoretical subword vocabulary size of 12, but you have only actually observed 5 different symbols.
