### ISSUE TITLE
what is num_operation?!

### ISSUE THREAD

**Issue by amirj** [rsennrich/subword-nmt#7]
./learn_bpe.py -s {num_operations} < {train_file} > {codes_file}

what is num_operations and how to set it?

I think it maybe the number of tokens in the final vocabulary, so I executed the above command using 30000 for 'num_operations' parameter on a machine with 32GB of memory.
After two days, it's still running while takes all the available memory (32GB) + 15GB of swap space.
Is it normal?!

**Comment by rsennrich** [comment]
Hello Amir,

num_operations is the number of BPE merge operations that are learned. 
The final vocabulary is the character vocabulary + num_operations.

Are you by any chance applying BPE to a text that is not word-segmented, 
such as Chinese? The code first extracts the word vocabulary, then 
learns the operations on this vocabulary, without allowing cross-word 
merging of symbols. A text without word segmentation breaks this assumption.

best wishes,
Rico

**Comment by amirj** [comment]
No, this is an english corpus, segmented to appropriate tokens.
I think the problem is that the number of tokens in my corpus is very large (3M), since it is crawled from the web. What is the normal value for 'num_operations' parameter for english language? If it set to 20K, it covers how many tokens? (roughly)

**Comment by rsennrich** [comment]
I've run the scripts on tens of millions of sentences without problems. 3M tokens should not be a problem. Since your data is crawled from the web, I've seen websites that use some special unicode whitespace characters instead of the normal space, which could cause the same effect as non-segmented Chinese, namely that the full line is treated as a single word. You could double-check by printing the vocab (line 62 in learn_bpe.py), and/or its size.

I've seen values between 30k and 90k used for English, but I don't know which setting is optimal empirically.

**Comment by amirj** [comment]
Thank you.
